CREATE TABLE BRANCH (
	BRANCH_ID       VARCHAR2(10)   NOT NULL,
	BRANCH_NAME     VARCHAR2(100)  NOT NULL,
	LATITUDE        NUMBER(9,6)    NOT NULL,
	LONGITUDE       NUMBER(9,6)    NOT NULL,
	OPENING_RESERVE NUMBER(15,2)   NOT NULL,
	CURRENT_RESERVE NUMBER(15,2)   NOT NULL,
	MIN_THRESHOLD_PCT NUMBER(5,2)  NOT NULL,
	CONSTRAINT PK_BRANCH PRIMARY KEY (BRANCH_ID)
);

CREATE TABLE APP_USER (
	USER_ID       VARCHAR2(36)  NOT NULL,
	USERNAME      VARCHAR2(50)  NOT NULL,
	PASSWORD_HASH VARCHAR2(255) NOT NULL,
	CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
	CONSTRAINT PK_APP_USER PRIMARY KEY (USER_ID),
	CONSTRAINT UQ_APP_USER_USERNAME UNIQUE (USERNAME)
);
