CREATE TABLE CASH_TRANSACTION (
	TRANSACTION_ID VARCHAR2(36) NOT NULL,
	BRANCH_ID      VARCHAR2(10) NOT NULL,
	TXN_TYPE       VARCHAR2(20) NOT NULL,
	AMOUNT         NUMBER(15,2) NOT NULL,
	EVENT_TIMESTAMP TIMESTAMP NOT NULL,
	CONSTRAINT PK_CASH_TXN PRIMARY KEY (TRANSACTION_ID),
	CONSTRAINT CK_CASH_TXN_TYPE CHECK (TXN_TYPE IN ('DEPOSIT', 'WITHDRAWAL')),
	CONSTRAINT CK_CASH_TXN_AMOUNT CHECK (AMOUNT > 0)
);

CREATE INDEX IX_CASH_TXN_BRANCH ON CASH_TRANSACTION (BRANCH_ID, EVENT_TIMESTAMP);
