CREATE TABLE FORECAST_SNAPSHOT (
	FORECAST_ID VARCHAR2(36) NOT NULL,
	BRANCH_ID VARCHAR2(10) NOT NULL,
	FORECAST_DATE DATE NOT NULL,
	PREDICTED_POSITION NUMBER(15,2) NOT NULL,
	CONFIDENCE_BAND_LOW NUMBER(15,2) NOT NULL,
	CONFIDENCE_BAND_HIGH NUMBER(15,2) NOT NULL,
	ACTUAL_POSITION NUMBER(15,2),
	CONSTRAINT PK_FORECAST PRIMARY KEY (FORECAST_ID)
);

CREATE INDEX IX_FORECAST_BRANCH_DATE ON FORECAST_SNAPSHOT (BRANCH_ID, FORECAST_DATE);
