CREATE TABLE TRANSFER_REQUEST (
	REQUEST_ID VARCHAR2(36) NOT NULL,
	SOURCE_BRANCH_ID VARCHAR2(10) NOT NULL,
	DESTINATION_BRANCH_ID VARCHAR2(10) NOT NULL,
	AMOUNT NUMBER(15,2) NOT NULL,
	STATUS VARCHAR2(20) NOT NULL,
	REQUESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
	CONSTRAINT PK_TRANSFER_REQ PRIMARY KEY (REQUEST_ID),
	CONSTRAINT CK_TRANSFER_STATUS CHECK (STATUS IN ('REQUESTED', 'APPROVED', 'DISPATCHED', 'DELIVERED')),
	CONSTRAINT CK_TRANSFER_AMOUNT CHECK (AMOUNT > 0)
);
