-- Demo-only history for the 14-day cash-health forecast.
-- Run after 01_branch.sql and 02_cash_transaction.sql.
-- It creates varied EOD movement for all four seeded branches.

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP)
SELECT RAWTOHEX(SYS_GUID()), b.BRANCH_ID,
       CASE WHEN MOD(d.DAY_NO + b.BRANCH_NO, 5) IN (0, 1) THEN 'WITHDRAWAL' ELSE 'DEPOSIT' END,
       CASE
         WHEN MOD(d.DAY_NO + b.BRANCH_NO, 5) IN (0, 1)
           THEN 18000 + MOD(d.DAY_NO * 731 + b.BRANCH_NO * 1900, 26000)
         ELSE 26000 + MOD(d.DAY_NO * 941 + b.BRANCH_NO * 2300, 42000)
       END,
       TRUNC(SYSDATE) - 13 + d.DAY_NO - 1 + (10 + MOD(d.DAY_NO * 3 + b.BRANCH_NO, 8)) / 24
FROM (
  SELECT 'BR001' BRANCH_ID, 1 BRANCH_NO FROM DUAL UNION ALL
  SELECT 'BR002', 2 FROM DUAL UNION ALL
  SELECT 'BR003', 3 FROM DUAL UNION ALL
  SELECT 'BR004', 4 FROM DUAL
) b
CROSS JOIN (SELECT LEVEL DAY_NO FROM DUAL CONNECT BY LEVEL <= 14) d;

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP)
SELECT RAWTOHEX(SYS_GUID()), b.BRANCH_ID, 'DEPOSIT',
       42000 + MOD(d.DAY_NO * 613 + b.BRANCH_NO * 1700, 38000),
       TRUNC(SYSDATE) - 13 + d.DAY_NO - 1 + (15 + MOD(d.DAY_NO * 5 + b.BRANCH_NO, 7)) / 24
FROM (
  SELECT 'BR001' BRANCH_ID, 1 BRANCH_NO FROM DUAL UNION ALL
  SELECT 'BR002', 2 FROM DUAL UNION ALL
  SELECT 'BR003', 3 FROM DUAL UNION ALL
  SELECT 'BR004', 4 FROM DUAL
) b
CROSS JOIN (SELECT LEVEL DAY_NO FROM DUAL CONNECT BY LEVEL <= 14) d;

COMMIT;
