-- Fresh seed script: 08_seed_fresh_history.sql
-- Run after 01_branch.sql and 02_cash_transaction.sql.
-- Cleans existing transactions and seeds fresh 14-day history with BR004 facing heavy withdrawal pressure.

-- 1. Clean existing transactions
DELETE FROM CASH_TRANSACTION;

-- 2. Reset initial branch reserves
UPDATE BRANCH SET CURRENT_RESERVE = 500000 WHERE BRANCH_ID = 'BR001';
UPDATE BRANCH SET CURRENT_RESERVE = 750000 WHERE BRANCH_ID = 'BR002';
UPDATE BRANCH SET CURRENT_RESERVE = 400000 WHERE BRANCH_ID = 'BR003';
UPDATE BRANCH SET CURRENT_RESERVE = 120000 WHERE BRANCH_ID = 'BR004'; -- Depleted reserve for Thane

-- 3. Seed BR004 (Thane) Heavy Withdrawal Spikes over past 4 days
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'WITHDRAWAL', 120000, TRUNC(SYSDATE) - 3 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'DEPOSIT', 20000, TRUNC(SYSDATE) - 3 + 14/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'WITHDRAWAL', 150000, TRUNC(SYSDATE) - 2 + 11/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'DEPOSIT', 25000, TRUNC(SYSDATE) - 2 + 15/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'WITHDRAWAL', 180000, TRUNC(SYSDATE) - 1 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'DEPOSIT', 15000, TRUNC(SYSDATE) - 1 + 16/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'WITHDRAWAL', 95000, TRUNC(SYSDATE) + 9/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'DEPOSIT', 10000, TRUNC(SYSDATE) + 12/24);

-- 4. Seed BR002 (BKC) Healthy Surplus Inflows
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR002', 'DEPOSIT', 250000, TRUNC(SYSDATE) - 2 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR002', 'DEPOSIT', 210000, TRUNC(SYSDATE) - 1 + 11/24);

-- 5. Seed BR001 (Andheri) & BR003 (Powai) Normal Flow
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR001', 'DEPOSIT', 80000, TRUNC(SYSDATE) - 1 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR001', 'WITHDRAWAL', 65000, TRUNC(SYSDATE) - 1 + 15/24);

COMMIT;
