-- Seed script: 08_seed_rich_history.sql
-- Run after 01_branch.sql and 02_cash_transaction.sql.
-- Seeds rich historical transactions with heavy withdrawal surges and deposit inflows across 14 days.

-- 1. Heavy Withdrawal Trend for BR004 (Thane) over past 4 days (Creates Deficit Pressure)
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'WITHDRAWAL', 95000, TRUNC(SYSDATE) - 3 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'DEPOSIT', 25000, TRUNC(SYSDATE) - 3 + 14/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'WITHDRAWAL', 110000, TRUNC(SYSDATE) - 2 + 11/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'DEPOSIT', 30000, TRUNC(SYSDATE) - 2 + 15/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'WITHDRAWAL', 125000, TRUNC(SYSDATE) - 1 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'DEPOSIT', 20000, TRUNC(SYSDATE) - 1 + 16/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'WITHDRAWAL', 80000, TRUNC(SYSDATE) + 9/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR004', 'DEPOSIT', 15000, TRUNC(SYSDATE) + 12/24);

-- 2. Strong Surplus Deposit Inflow Trend for BR002 (BKC)
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR002', 'DEPOSIT', 180000, TRUNC(SYSDATE) - 3 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR002', 'WITHDRAWAL', 40000, TRUNC(SYSDATE) - 3 + 14/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR002', 'DEPOSIT', 220000, TRUNC(SYSDATE) - 2 + 11/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR002', 'WITHDRAWAL', 50000, TRUNC(SYSDATE) - 2 + 15/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR002', 'DEPOSIT', 190000, TRUNC(SYSDATE) - 1 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR002', 'WITHDRAWAL', 35000, TRUNC(SYSDATE) - 1 + 16/24);

-- 3. Balanced Operational Flow for BR001 (Andheri) and BR003 (Powai)
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR001', 'DEPOSIT', 75000, TRUNC(SYSDATE) - 2 + 10/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR001', 'WITHDRAWAL', 60000, TRUNC(SYSDATE) - 2 + 14/24);

INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR003', 'DEPOSIT', 50000, TRUNC(SYSDATE) - 1 + 11/24);
INSERT INTO CASH_TRANSACTION (TRANSACTION_ID, BRANCH_ID, TXN_TYPE, AMOUNT, EVENT_TIMESTAMP) VALUES
  (RAWTOHEX(SYS_GUID()), 'BR003', 'WITHDRAWAL', 55000, TRUNC(SYSDATE) - 1 + 15/24);

COMMIT;
