@echo off
setlocal
cd /d "%~dp0"
echo Branch Service source writer
if not exist "branch-service\src\main\java\com\bankdemo\branchservice" mkdir "branch-service\src\main\java\com\bankdemo\branchservice"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\BranchServiceApplication.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_BranchServiceApplication_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZTsKCmltcG9ydCBvcmcuc3ByaW5nZnJh
echo bWV3b3JrLmJvb3QuU3ByaW5nQXBwbGljYXRpb247CmltcG9ydCBvcmcuc3ByaW5nZnJhbWV3b3Jr
echo LmJvb3QuYXV0b2NvbmZpZ3VyZS5TcHJpbmdCb290QXBwbGljYXRpb247CgpAU3ByaW5nQm9vdEFw
echo cGxpY2F0aW9uCnB1YmxpYyBjbGFzcyBCcmFuY2hTZXJ2aWNlQXBwbGljYXRpb24gewogICAgcHVi
echo bGljIHN0YXRpYyB2b2lkIG1haW4oU3RyaW5nW10gYXJncykgewogICAgICAgIFNwcmluZ0FwcGxp
echo Y2F0aW9uLnJ1bihCcmFuY2hTZXJ2aWNlQXBwbGljYXRpb24uY2xhc3MsIGFyZ3MpOwogICAgfQp9
echo Cg==
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_BranchServiceApplication_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\BranchServiceApplication.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_BranchServiceApplication_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\entity" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\entity"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\entity\Branch.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_entity_Branch_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5lbnRpdHk7CgppbXBvcnQgamFrYXJ0
echo YS5wZXJzaXN0ZW5jZS4qOwppbXBvcnQgamF2YS5tYXRoLkJpZ0RlY2ltYWw7CgpARW50aXR5CkBU
echo YWJsZShuYW1lID0gIkJSQU5DSCIpCnB1YmxpYyBjbGFzcyBCcmFuY2ggewogICAgQElkIEBDb2x1
echo bW4obmFtZSA9ICJCUkFOQ0hfSUQiLCBsZW5ndGggPSAxMCkgcHJpdmF0ZSBTdHJpbmcgYnJhbmNo
echo SWQ7CiAgICBAQ29sdW1uKG5hbWUgPSAiQlJBTkNIX05BTUUiLCBudWxsYWJsZSA9IGZhbHNlLCBs
echo ZW5ndGggPSAxMDApIHByaXZhdGUgU3RyaW5nIGJyYW5jaE5hbWU7CiAgICBAQ29sdW1uKG5hbWUg
echo PSAiTEFUSVRVREUiLCBudWxsYWJsZSA9IGZhbHNlLCBwcmVjaXNpb24gPSA5LCBzY2FsZSA9IDYp
echo IHByaXZhdGUgQmlnRGVjaW1hbCBsYXRpdHVkZTsKICAgIEBDb2x1bW4obmFtZSA9ICJMT05HSVRV
echo REUiLCBudWxsYWJsZSA9IGZhbHNlLCBwcmVjaXNpb24gPSA5LCBzY2FsZSA9IDYpIHByaXZhdGUg
echo QmlnRGVjaW1hbCBsb25naXR1ZGU7CiAgICBAQ29sdW1uKG5hbWUgPSAiT1BFTklOR19SRVNFUlZF
echo IiwgbnVsbGFibGUgPSBmYWxzZSwgcHJlY2lzaW9uID0gMTUsIHNjYWxlID0gMikgcHJpdmF0ZSBC
echo aWdEZWNpbWFsIG9wZW5pbmdSZXNlcnZlOwogICAgQENvbHVtbihuYW1lID0gIkNVUlJFTlRfUkVT
echo RVJWRSIsIG51bGxhYmxlID0gZmFsc2UsIHByZWNpc2lvbiA9IDE1LCBzY2FsZSA9IDIpIHByaXZh
echo dGUgQmlnRGVjaW1hbCBjdXJyZW50UmVzZXJ2ZTsKICAgIEBDb2x1bW4obmFtZSA9ICJNSU5fVEhS
echo RVNIT0xEX1BDVCIsIG51bGxhYmxlID0gZmFsc2UsIHByZWNpc2lvbiA9IDUsIHNjYWxlID0gMikg
echo cHJpdmF0ZSBCaWdEZWNpbWFsIG1pblRocmVzaG9sZFBjdDsKICAgIHB1YmxpYyBTdHJpbmcgZ2V0
echo QnJhbmNoSWQoKXtyZXR1cm4gYnJhbmNoSWQ7fSBwdWJsaWMgdm9pZCBzZXRCcmFuY2hJZChTdHJp
echo bmcgdil7YnJhbmNoSWQ9djt9CiAgICBwdWJsaWMgU3RyaW5nIGdldEJyYW5jaE5hbWUoKXtyZXR1
echo cm4gYnJhbmNoTmFtZTt9IHB1YmxpYyB2b2lkIHNldEJyYW5jaE5hbWUoU3RyaW5nIHYpe2JyYW5j
echo aE5hbWU9djt9CiAgICBwdWJsaWMgQmlnRGVjaW1hbCBnZXRMYXRpdHVkZSgpe3JldHVybiBsYXRp
echo dHVkZTt9IHB1YmxpYyB2b2lkIHNldExhdGl0dWRlKEJpZ0RlY2ltYWwgdil7bGF0aXR1ZGU9djt9
echo CiAgICBwdWJsaWMgQmlnRGVjaW1hbCBnZXRMb25naXR1ZGUoKXtyZXR1cm4gbG9uZ2l0dWRlO30g
echo cHVibGljIHZvaWQgc2V0TG9uZ2l0dWRlKEJpZ0RlY2ltYWwgdil7bG9uZ2l0dWRlPXY7fQogICAg
echo cHVibGljIEJpZ0RlY2ltYWwgZ2V0T3BlbmluZ1Jlc2VydmUoKXtyZXR1cm4gb3BlbmluZ1Jlc2Vy
echo dmU7fSBwdWJsaWMgdm9pZCBzZXRPcGVuaW5nUmVzZXJ2ZShCaWdEZWNpbWFsIHYpe29wZW5pbmdS
echo ZXNlcnZlPXY7fQogICAgcHVibGljIEJpZ0RlY2ltYWwgZ2V0Q3VycmVudFJlc2VydmUoKXtyZXR1
echo cm4gY3VycmVudFJlc2VydmU7fSBwdWJsaWMgdm9pZCBzZXRDdXJyZW50UmVzZXJ2ZShCaWdEZWNp
echo bWFsIHYpe2N1cnJlbnRSZXNlcnZlPXY7fQogICAgcHVibGljIEJpZ0RlY2ltYWwgZ2V0TWluVGhy
echo ZXNob2xkUGN0KCl7cmV0dXJuIG1pblRocmVzaG9sZFBjdDt9IHB1YmxpYyB2b2lkIHNldE1pblRo
echo cmVzaG9sZFBjdChCaWdEZWNpbWFsIHYpe21pblRocmVzaG9sZFBjdD12O30KfQo=
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_entity_Branch_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\entity\Branch.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_entity_Branch_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\entity" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\entity"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\entity\AppUser.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_entity_AppUser_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5lbnRpdHk7CgppbXBvcnQgamFrYXJ0
echo YS5wZXJzaXN0ZW5jZS4qOwppbXBvcnQgamF2YS50aW1lLkxvY2FsRGF0ZVRpbWU7CgpARW50aXR5
echo CkBUYWJsZShuYW1lID0gIkFQUF9VU0VSIikKcHVibGljIGNsYXNzIEFwcFVzZXIgewogICAgQElk
echo IEBDb2x1bW4obmFtZSA9ICJVU0VSX0lEIiwgbGVuZ3RoID0gMzYpIHByaXZhdGUgU3RyaW5nIHVz
echo ZXJJZDsKICAgIEBDb2x1bW4obmFtZSA9ICJVU0VSTkFNRSIsIG51bGxhYmxlID0gZmFsc2UsIHVu
echo aXF1ZSA9IHRydWUsIGxlbmd0aCA9IDUwKSBwcml2YXRlIFN0cmluZyB1c2VybmFtZTsKICAgIEBD
echo b2x1bW4obmFtZSA9ICJQQVNTV09SRF9IQVNIIiwgbnVsbGFibGUgPSBmYWxzZSwgbGVuZ3RoID0g
echo MjU1KSBwcml2YXRlIFN0cmluZyBwYXNzd29yZEhhc2g7CiAgICBAQ29sdW1uKG5hbWUgPSAiQ1JF
echo QVRFRF9BVCIpIHByaXZhdGUgTG9jYWxEYXRlVGltZSBjcmVhdGVkQXQ7CiAgICBwdWJsaWMgU3Ry
echo aW5nIGdldFVzZXJJZCgpe3JldHVybiB1c2VySWQ7fSBwdWJsaWMgdm9pZCBzZXRVc2VySWQoU3Ry
echo aW5nIHYpe3VzZXJJZD12O30KICAgIHB1YmxpYyBTdHJpbmcgZ2V0VXNlcm5hbWUoKXtyZXR1cm4g
echo dXNlcm5hbWU7fSBwdWJsaWMgdm9pZCBzZXRVc2VybmFtZShTdHJpbmcgdil7dXNlcm5hbWU9djt9
echo CiAgICBwdWJsaWMgU3RyaW5nIGdldFBhc3N3b3JkSGFzaCgpe3JldHVybiBwYXNzd29yZEhhc2g7
echo fSBwdWJsaWMgdm9pZCBzZXRQYXNzd29yZEhhc2goU3RyaW5nIHYpe3Bhc3N3b3JkSGFzaD12O30K
echo ICAgIHB1YmxpYyBMb2NhbERhdGVUaW1lIGdldENyZWF0ZWRBdCgpe3JldHVybiBjcmVhdGVkQXQ7
echo fSBwdWJsaWMgdm9pZCBzZXRDcmVhdGVkQXQoTG9jYWxEYXRlVGltZSB2KXtjcmVhdGVkQXQ9djt9
echo Cn0K
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_entity_AppUser_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\entity\AppUser.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_entity_AppUser_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\repository" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\repository"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\repository\BranchRepository.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_repository_BranchRepository_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5yZXBvc2l0b3J5OwppbXBvcnQgY29t
echo LmJhbmtkZW1vLmJyYW5jaHNlcnZpY2UuZW50aXR5LkJyYW5jaDsKaW1wb3J0IG9yZy5zcHJpbmdm
echo cmFtZXdvcmsuZGF0YS5qcGEucmVwb3NpdG9yeS5KcGFSZXBvc2l0b3J5OwpwdWJsaWMgaW50ZXJm
echo YWNlIEJyYW5jaFJlcG9zaXRvcnkgZXh0ZW5kcyBKcGFSZXBvc2l0b3J5PEJyYW5jaCxTdHJpbmc+
echo IHt9Cg==
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_repository_BranchRepository_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\repository\BranchRepository.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_repository_BranchRepository_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\repository" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\repository"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\repository\AppUserRepository.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_repository_AppUserRepository_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5yZXBvc2l0b3J5OwppbXBvcnQgY29t
echo LmJhbmtkZW1vLmJyYW5jaHNlcnZpY2UuZW50aXR5LkFwcFVzZXI7CmltcG9ydCBvcmcuc3ByaW5n
echo ZnJhbWV3b3JrLmRhdGEuanBhLnJlcG9zaXRvcnkuSnBhUmVwb3NpdG9yeTsKaW1wb3J0IGphdmEu
echo dXRpbC5PcHRpb25hbDsKcHVibGljIGludGVyZmFjZSBBcHBVc2VyUmVwb3NpdG9yeSBleHRlbmRz
echo IEpwYVJlcG9zaXRvcnk8QXBwVXNlcixTdHJpbmc+IHsgT3B0aW9uYWw8QXBwVXNlcj4gZmluZEJ5
echo VXNlcm5hbWUoU3RyaW5nIHVzZXJuYW1lKTsgfQo=
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_repository_AppUserRepository_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\repository\AppUserRepository.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_repository_AppUserRepository_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\dto" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\dto"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\dto\BranchDto.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_BranchDto_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5kdG87CmltcG9ydCBqYXZhLm1hdGgu
echo QmlnRGVjaW1hbDsKcHVibGljIGNsYXNzIEJyYW5jaER0byB7CiBwcml2YXRlIFN0cmluZyBicmFu
echo Y2hJZCwgYnJhbmNoTmFtZTsgcHJpdmF0ZSBCaWdEZWNpbWFsIGxhdGl0dWRlLCBsb25naXR1ZGUs
echo IGN1cnJlbnRSZXNlcnZlLCBtaW5UaHJlc2hvbGRQY3Q7CiBwdWJsaWMgU3RyaW5nIGdldEJyYW5j
echo aElkKCl7cmV0dXJuIGJyYW5jaElkO30gcHVibGljIHZvaWQgc2V0QnJhbmNoSWQoU3RyaW5nIHYp
echo e2JyYW5jaElkPXY7fQogcHVibGljIFN0cmluZyBnZXRCcmFuY2hOYW1lKCl7cmV0dXJuIGJyYW5j
echo aE5hbWU7fSBwdWJsaWMgdm9pZCBzZXRCcmFuY2hOYW1lKFN0cmluZyB2KXticmFuY2hOYW1lPXY7
echo fQogcHVibGljIEJpZ0RlY2ltYWwgZ2V0TGF0aXR1ZGUoKXtyZXR1cm4gbGF0aXR1ZGU7fSBwdWJs
echo aWMgdm9pZCBzZXRMYXRpdHVkZShCaWdEZWNpbWFsIHYpe2xhdGl0dWRlPXY7fQogcHVibGljIEJp
echo Z0RlY2ltYWwgZ2V0TG9uZ2l0dWRlKCl7cmV0dXJuIGxvbmdpdHVkZTt9IHB1YmxpYyB2b2lkIHNl
echo dExvbmdpdHVkZShCaWdEZWNpbWFsIHYpe2xvbmdpdHVkZT12O30KIHB1YmxpYyBCaWdEZWNpbWFs
echo IGdldEN1cnJlbnRSZXNlcnZlKCl7cmV0dXJuIGN1cnJlbnRSZXNlcnZlO30gcHVibGljIHZvaWQg
echo c2V0Q3VycmVudFJlc2VydmUoQmlnRGVjaW1hbCB2KXtjdXJyZW50UmVzZXJ2ZT12O30KIHB1Ymxp
echo YyBCaWdEZWNpbWFsIGdldE1pblRocmVzaG9sZFBjdCgpe3JldHVybiBtaW5UaHJlc2hvbGRQY3Q7
echo fSBwdWJsaWMgdm9pZCBzZXRNaW5UaHJlc2hvbGRQY3QoQmlnRGVjaW1hbCB2KXttaW5UaHJlc2hv
echo bGRQY3Q9djt9Cn0K
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_BranchDto_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\dto\BranchDto.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_BranchDto_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\dto" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\dto"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\dto\ThresholdUpdateRequest.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_ThresholdUpdateRequest_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5kdG87CmltcG9ydCBqYXZhLm1hdGgu
echo QmlnRGVjaW1hbDsKcHVibGljIGNsYXNzIFRocmVzaG9sZFVwZGF0ZVJlcXVlc3QgeyBwcml2YXRl
echo IEJpZ0RlY2ltYWwgbWluVGhyZXNob2xkUGN0OyBwdWJsaWMgQmlnRGVjaW1hbCBnZXRNaW5UaHJl
echo c2hvbGRQY3QoKXtyZXR1cm4gbWluVGhyZXNob2xkUGN0O30gcHVibGljIHZvaWQgc2V0TWluVGhy
echo ZXNob2xkUGN0KEJpZ0RlY2ltYWwgdil7bWluVGhyZXNob2xkUGN0PXY7fSB9Cg==
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_ThresholdUpdateRequest_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\dto\ThresholdUpdateRequest.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_ThresholdUpdateRequest_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\dto" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\dto"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\dto\LoginRequest.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_LoginRequest_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5kdG87CnB1YmxpYyBjbGFzcyBMb2dp
echo blJlcXVlc3QgeyBwcml2YXRlIFN0cmluZyB1c2VybmFtZSxwYXNzd29yZDsgcHVibGljIFN0cmlu
echo ZyBnZXRVc2VybmFtZSgpe3JldHVybiB1c2VybmFtZTt9IHB1YmxpYyB2b2lkIHNldFVzZXJuYW1l
echo KFN0cmluZyB2KXt1c2VybmFtZT12O30gcHVibGljIFN0cmluZyBnZXRQYXNzd29yZCgpe3JldHVy
echo biBwYXNzd29yZDt9IHB1YmxpYyB2b2lkIHNldFBhc3N3b3JkKFN0cmluZyB2KXtwYXNzd29yZD12
echo O30gfQo=
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_LoginRequest_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\dto\LoginRequest.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_LoginRequest_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\dto" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\dto"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\dto\LoginResponse.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_LoginResponse_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5kdG87CnB1YmxpYyBjbGFzcyBMb2dp
echo blJlc3BvbnNlIHsgcHJpdmF0ZSBTdHJpbmcgdG9rZW47IHB1YmxpYyBMb2dpblJlc3BvbnNlKCl7
echo fSBwdWJsaWMgTG9naW5SZXNwb25zZShTdHJpbmcgdG9rZW4pe3RoaXMudG9rZW49dG9rZW47fSBw
echo dWJsaWMgU3RyaW5nIGdldFRva2VuKCl7cmV0dXJuIHRva2VuO30gcHVibGljIHZvaWQgc2V0VG9r
echo ZW4oU3RyaW5nIHYpe3Rva2VuPXY7fSB9Cg==
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_LoginResponse_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\dto\LoginResponse.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_dto_LoginResponse_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\service" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\service"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\service\BranchService.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_service_BranchService_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5zZXJ2aWNlOwppbXBvcnQgY29tLmJh
echo bmtkZW1vLmJyYW5jaHNlcnZpY2UuZHRvLkJyYW5jaER0bzsKaW1wb3J0IGphdmEubWF0aC5CaWdE
echo ZWNpbWFsOwppbXBvcnQgamF2YS51dGlsLkxpc3Q7CnB1YmxpYyBpbnRlcmZhY2UgQnJhbmNoU2Vy
echo dmljZSB7IExpc3Q8QnJhbmNoRHRvPiBnZXRBbGxCcmFuY2hlcygpOyBCcmFuY2hEdG8gZ2V0QnJh
echo bmNoKFN0cmluZyBicmFuY2hJZCk7IEJyYW5jaER0byB1cGRhdGVUaHJlc2hvbGQoU3RyaW5nIGJy
echo YW5jaElkLCBCaWdEZWNpbWFsIG1pblRocmVzaG9sZFBjdCk7IEJyYW5jaER0byBhZGp1c3RSZXNl
echo cnZlKFN0cmluZyBicmFuY2hJZCwgQmlnRGVjaW1hbCBkZWx0YSk7IH0K
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_service_BranchService_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\service\BranchService.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_service_BranchService_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\service" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\service"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\service\BranchServiceImpl.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_service_BranchServiceImpl_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5zZXJ2aWNlOwppbXBvcnQgY29tLmJh
echo bmtkZW1vLmJyYW5jaHNlcnZpY2UuZHRvLkJyYW5jaER0bzsKaW1wb3J0IGNvbS5iYW5rZGVtby5i
echo cmFuY2hzZXJ2aWNlLmVudGl0eS5CcmFuY2g7CmltcG9ydCBjb20uYmFua2RlbW8uYnJhbmNoc2Vy
echo dmljZS5yZXBvc2l0b3J5LkJyYW5jaFJlcG9zaXRvcnk7CmltcG9ydCBvcmcuc3ByaW5nZnJhbWV3
echo b3JrLnN0ZXJlb3R5cGUuU2VydmljZTsKaW1wb3J0IG9yZy5zcHJpbmdmcmFtZXdvcmsudHJhbnNh
echo Y3Rpb24uYW5ub3RhdGlvbi5UcmFuc2FjdGlvbmFsOwppbXBvcnQgamF2YS5tYXRoLkJpZ0RlY2lt
echo YWw7CmltcG9ydCBqYXZhLnV0aWwuTGlzdDsKQFNlcnZpY2UgcHVibGljIGNsYXNzIEJyYW5jaFNl
echo cnZpY2VJbXBsIGltcGxlbWVudHMgQnJhbmNoU2VydmljZSB7CiBwcml2YXRlIGZpbmFsIEJyYW5j
echo aFJlcG9zaXRvcnkgcmVwbzsgcHVibGljIEJyYW5jaFNlcnZpY2VJbXBsKEJyYW5jaFJlcG9zaXRv
echo cnkgcmVwbyl7dGhpcy5yZXBvPXJlcG87fQogQFRyYW5zYWN0aW9uYWwocmVhZE9ubHk9dHJ1ZSkg
echo cHVibGljIExpc3Q8QnJhbmNoRHRvPiBnZXRBbGxCcmFuY2hlcygpe3JldHVybiByZXBvLmZpbmRB
echo bGwoKS5zdHJlYW0oKS5tYXAodGhpczo6dG9EdG8pLnRvTGlzdCgpO30KIEBUcmFuc2FjdGlvbmFs
echo KHJlYWRPbmx5PXRydWUpIHB1YmxpYyBCcmFuY2hEdG8gZ2V0QnJhbmNoKFN0cmluZyBpZCl7cmV0
echo dXJuIHJlcG8uZmluZEJ5SWQoaWQpLm1hcCh0aGlzOjp0b0R0bykub3JFbHNlVGhyb3coKCktPm5l
echo dyBJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24oIlVua25vd24gYnJhbmNoSWQ6ICIraWQpKTt9CiBA
echo VHJhbnNhY3Rpb25hbCBwdWJsaWMgQnJhbmNoRHRvIHVwZGF0ZVRocmVzaG9sZChTdHJpbmcgaWQs
echo QmlnRGVjaW1hbCBwY3Qpe2lmKHBjdD09bnVsbHx8cGN0LmNvbXBhcmVUbyhCaWdEZWNpbWFsLlpF
echo Uk8pPDB8fHBjdC5jb21wYXJlVG8oQmlnRGVjaW1hbC52YWx1ZU9mKDEwMCkpPjApIHRocm93IG5l
echo dyBJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24oIm1pblRocmVzaG9sZFBjdCBtdXN0IGJlIGJldHdl
echo ZW4gMCBhbmQgMTAwIik7IEJyYW5jaCBiPXJlcG8uZmluZEJ5SWQoaWQpLm9yRWxzZVRocm93KCgp
echo LT5uZXcgSWxsZWdhbEFyZ3VtZW50RXhjZXB0aW9uKCJVbmtub3duIGJyYW5jaElkOiAiK2lkKSk7
echo IGIuc2V0TWluVGhyZXNob2xkUGN0KHBjdCk7IHJldHVybiB0b0R0byhyZXBvLnNhdmUoYikpO30K
echo IEBUcmFuc2FjdGlvbmFsIHB1YmxpYyBCcmFuY2hEdG8gYWRqdXN0UmVzZXJ2ZShTdHJpbmcgaWQs
echo QmlnRGVjaW1hbCBkZWx0YSl7aWYoZGVsdGE9PW51bGwpIHRocm93IG5ldyBJbGxlZ2FsQXJndW1l
echo bnRFeGNlcHRpb24oImRlbHRhIGlzIHJlcXVpcmVkIik7IEJyYW5jaCBiPXJlcG8uZmluZEJ5SWQo
echo aWQpLm9yRWxzZVRocm93KCgpLT5uZXcgSWxsZWdhbEFyZ3VtZW50RXhjZXB0aW9uKCJVbmtub3du
echo IGJyYW5jaElkOiAiK2lkKSk7IGIuc2V0Q3VycmVudFJlc2VydmUoYi5nZXRDdXJyZW50UmVzZXJ2
echo ZSgpLmFkZChkZWx0YSkpOyByZXR1cm4gdG9EdG8ocmVwby5zYXZlKGIpKTt9CiBwcml2YXRlIEJy
echo YW5jaER0byB0b0R0byhCcmFuY2ggYil7QnJhbmNoRHRvIGQ9bmV3IEJyYW5jaER0bygpOyBkLnNl
echo dEJyYW5jaElkKGIuZ2V0QnJhbmNoSWQoKSk7IGQuc2V0QnJhbmNoTmFtZShiLmdldEJyYW5jaE5h
echo bWUoKSk7IGQuc2V0TGF0aXR1ZGUoYi5nZXRMYXRpdHVkZSgpKTsgZC5zZXRMb25naXR1ZGUoYi5n
echo ZXRMb25naXR1ZGUoKSk7IGQuc2V0Q3VycmVudFJlc2VydmUoYi5nZXRDdXJyZW50UmVzZXJ2ZSgp
echo KTsgZC5zZXRNaW5UaHJlc2hvbGRQY3QoYi5nZXRNaW5UaHJlc2hvbGRQY3QoKSk7IHJldHVybiBk
echo O30KfQo=
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_service_BranchServiceImpl_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\service\BranchServiceImpl.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_service_BranchServiceImpl_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\controller" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\controller"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\controller\BranchController.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_controller_BranchController_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5jb250cm9sbGVyOwppbXBvcnQgY29t
echo LmJhbmtkZW1vLmJyYW5jaHNlcnZpY2UuZHRvLio7CmltcG9ydCBjb20uYmFua2RlbW8uYnJhbmNo
echo c2VydmljZS5zZXJ2aWNlLkJyYW5jaFNlcnZpY2U7CmltcG9ydCBvcmcuc3ByaW5nZnJhbWV3b3Jr
echo LndlYi5iaW5kLmFubm90YXRpb24uKjsKaW1wb3J0IGphdmEubWF0aC5CaWdEZWNpbWFsOwppbXBv
echo cnQgamF2YS51dGlsLkxpc3Q7CkBSZXN0Q29udHJvbGxlciBAUmVxdWVzdE1hcHBpbmcoIi9hcGkv
echo YnJhbmNoZXMiKSBwdWJsaWMgY2xhc3MgQnJhbmNoQ29udHJvbGxlciB7CiBwcml2YXRlIGZpbmFs
echo IEJyYW5jaFNlcnZpY2Ugc2VydmljZTsgcHVibGljIEJyYW5jaENvbnRyb2xsZXIoQnJhbmNoU2Vy
echo dmljZSBzZXJ2aWNlKXt0aGlzLnNlcnZpY2U9c2VydmljZTt9CiBAR2V0TWFwcGluZyBwdWJsaWMg
echo TGlzdDxCcmFuY2hEdG8+IGdldEFsbEJyYW5jaGVzKCl7cmV0dXJuIHNlcnZpY2UuZ2V0QWxsQnJh
echo bmNoZXMoKTt9CiBAR2V0TWFwcGluZygiL3ticmFuY2hJZH0iKSBwdWJsaWMgQnJhbmNoRHRvIGdl
echo dEJyYW5jaChAUGF0aFZhcmlhYmxlIFN0cmluZyBicmFuY2hJZCl7cmV0dXJuIHNlcnZpY2UuZ2V0
echo QnJhbmNoKGJyYW5jaElkKTt9CiBAUHV0TWFwcGluZygiL3ticmFuY2hJZH0vdGhyZXNob2xkIikg
echo cHVibGljIEJyYW5jaER0byB1cGRhdGVUaHJlc2hvbGQoQFBhdGhWYXJpYWJsZSBTdHJpbmcgYnJh
echo bmNoSWQsQFJlcXVlc3RCb2R5IFRocmVzaG9sZFVwZGF0ZVJlcXVlc3QgcmVxKXtyZXR1cm4gc2Vy
echo dmljZS51cGRhdGVUaHJlc2hvbGQoYnJhbmNoSWQscmVxLmdldE1pblRocmVzaG9sZFBjdCgpKTt9
echo CiBAUGF0Y2hNYXBwaW5nKCIve2JyYW5jaElkfS9yZXNlcnZlIikgcHVibGljIEJyYW5jaER0byBh
echo ZGp1c3RSZXNlcnZlKEBQYXRoVmFyaWFibGUgU3RyaW5nIGJyYW5jaElkLEBSZXF1ZXN0Qm9keSBC
echo aWdEZWNpbWFsIGRlbHRhKXtyZXR1cm4gc2VydmljZS5hZGp1c3RSZXNlcnZlKGJyYW5jaElkLGRl
echo bHRhKTt9Cn0K
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_controller_BranchController_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\controller\BranchController.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_controller_BranchController_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\service" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\service"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\service\AuthService.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_service_AuthService_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5zZXJ2aWNlOwppbXBvcnQgY29tLmJh
echo bmtkZW1vLmJyYW5jaHNlcnZpY2UuZHRvLkxvZ2luUmVzcG9uc2U7CnB1YmxpYyBpbnRlcmZhY2Ug
echo QXV0aFNlcnZpY2UgeyBMb2dpblJlc3BvbnNlIGxvZ2luKFN0cmluZyB1c2VybmFtZSxTdHJpbmcg
echo cGFzc3dvcmQpOyB9Cg==
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_service_AuthService_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\service\AuthService.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_service_AuthService_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\service" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\service"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\service\AuthServiceImpl.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_service_AuthServiceImpl_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5zZXJ2aWNlOwoKaW1wb3J0IGNvbS5i
echo YW5rZGVtby5icmFuY2hzZXJ2aWNlLmR0by5Mb2dpblJlc3BvbnNlOwppbXBvcnQgY29tLmJhbmtk
echo ZW1vLmJyYW5jaHNlcnZpY2UuZW50aXR5LkFwcFVzZXI7CmltcG9ydCBjb20uYmFua2RlbW8uYnJh
echo bmNoc2VydmljZS5yZXBvc2l0b3J5LkFwcFVzZXJSZXBvc2l0b3J5OwppbXBvcnQgb3JnLnNwcmlu
echo Z2ZyYW1ld29yay5zZWN1cml0eS5jcnlwdG8ucGFzc3dvcmQuUGFzc3dvcmRFbmNvZGVyOwppbXBv
echo cnQgb3JnLnNwcmluZ2ZyYW1ld29yay5zdGVyZW90eXBlLlNlcnZpY2U7CgppbXBvcnQgamF2YXgu
echo Y3J5cHRvLk1hYzsKaW1wb3J0IGphdmF4LmNyeXB0by5zcGVjLlNlY3JldEtleVNwZWM7CmltcG9y
echo dCBqYXZhLm5pby5jaGFyc2V0LlN0YW5kYXJkQ2hhcnNldHM7CmltcG9ydCBqYXZhLnRpbWUuSW5z
echo dGFudDsKaW1wb3J0IGphdmEudXRpbC5CYXNlNjQ7CgpAU2VydmljZQpwdWJsaWMgY2xhc3MgQXV0
echo aFNlcnZpY2VJbXBsIGltcGxlbWVudHMgQXV0aFNlcnZpY2UgewogICAgcHJpdmF0ZSBzdGF0aWMg
echo ZmluYWwgbG9uZyBFWFBJUllfU0VDT05EUyA9IDI0ICogNjAgKiA2MDsKICAgIHByaXZhdGUgZmlu
echo YWwgQXBwVXNlclJlcG9zaXRvcnkgcmVwbzsKICAgIHByaXZhdGUgZmluYWwgUGFzc3dvcmRFbmNv
echo ZGVyIGVuY29kZXI7CgogICAgcHVibGljIEF1dGhTZXJ2aWNlSW1wbChBcHBVc2VyUmVwb3NpdG9y
echo eSByZXBvLCBQYXNzd29yZEVuY29kZXIgZW5jb2RlcikgewogICAgICAgIHRoaXMucmVwbyA9IHJl
echo cG87CiAgICAgICAgdGhpcy5lbmNvZGVyID0gZW5jb2RlcjsKICAgIH0KCiAgICBAT3ZlcnJpZGUK
echo ICAgIHB1YmxpYyBMb2dpblJlc3BvbnNlIGxvZ2luKFN0cmluZyB1c2VybmFtZSwgU3RyaW5nIHBh
echo c3N3b3JkKSB7CiAgICAgICAgQXBwVXNlciB1c2VyID0gcmVwby5maW5kQnlVc2VybmFtZSh1c2Vy
echo bmFtZSkKICAgICAgICAgICAgICAgIC5vckVsc2VUaHJvdygoKSAtPiBuZXcgSWxsZWdhbEFyZ3Vt
echo ZW50RXhjZXB0aW9uKCJJbnZhbGlkIHVzZXJuYW1lIG9yIHBhc3N3b3JkIikpOwogICAgICAgIGlm
echo ICghZW5jb2Rlci5tYXRjaGVzKHBhc3N3b3JkLCB1c2VyLmdldFBhc3N3b3JkSGFzaCgpKSkgewog
echo ICAgICAgICAgICB0aHJvdyBuZXcgSWxsZWdhbEFyZ3VtZW50RXhjZXB0aW9uKCJJbnZhbGlkIHVz
echo ZXJuYW1lIG9yIHBhc3N3b3JkIik7CiAgICAgICAgfQogICAgICAgIGxvbmcgbm93ID0gSW5zdGFu
echo dC5ub3coKS5nZXRFcG9jaFNlY29uZCgpOwogICAgICAgIGxvbmcgZXhwID0gbm93ICsgRVhQSVJZ
echo X1NFQ09ORFM7CiAgICAgICAgU3RyaW5nIGhlYWRlciA9IGJhc2U2NFVybCgieyJhbGciOiJIUzI1
echo NiIsInR5cCI6IkpXVCJ9Iik7CiAgICAgICAgU3RyaW5nIHBheWxvYWQgPSBiYXNlNjRVcmwoInsi
echo c3ViIjoiIiArIGVzY2FwZSh1c2VybmFtZSkgKyAiIiwicm9sZSI6IlVTRVIiLCJpYXQiOiIgKyBu
echo b3cgKyAiLCJleHAiOiIgKyBleHAgKyAifSIpOwogICAgICAgIFN0cmluZyBpbnB1dCA9IGhlYWRl
echo ciArICIuIiArIHBheWxvYWQ7CiAgICAgICAgcmV0dXJuIG5ldyBMb2dpblJlc3BvbnNlKGlucHV0
echo ICsgIi4iICsgc2lnbihpbnB1dCwgc2VjcmV0KCkpKTsKICAgIH0KCiAgICBwcml2YXRlIFN0cmlu
echo ZyBzZWNyZXQoKSB7CiAgICAgICAgU3RyaW5nIHZhbHVlID0gU3lzdGVtLmdldGVudigiSldUX1NF
echo Q1JFVCIpOwogICAgICAgIHJldHVybiB2YWx1ZSA9PSBudWxsIHx8IHZhbHVlLmlzQmxhbmsoKSA/
echo ICJicmFuY2gtY2FzaC1kZW1vLWxvY2FsLWp3dC1zZWNyZXQtY2hhbmdlLW1lIiA6IHZhbHVlOwog
echo ICAgfQoKICAgIHByaXZhdGUgU3RyaW5nIHNpZ24oU3RyaW5nIGlucHV0LCBTdHJpbmcgc2VjcmV0
echo KSB7CiAgICAgICAgdHJ5IHsKICAgICAgICAgICAgTWFjIG1hYyA9IE1hYy5nZXRJbnN0YW5jZSgi
echo SG1hY1NIQTI1NiIpOwogICAgICAgICAgICBtYWMuaW5pdChuZXcgU2VjcmV0S2V5U3BlYyhzZWNy
echo ZXQuZ2V0Qnl0ZXMoU3RhbmRhcmRDaGFyc2V0cy5VVEZfOCksICJIbWFjU0hBMjU2IikpOwogICAg
echo ICAgICAgICByZXR1cm4gQmFzZTY0LmdldFVybEVuY29kZXIoKS53aXRob3V0UGFkZGluZygpLmVu
echo Y29kZVRvU3RyaW5nKG1hYy5kb0ZpbmFsKGlucHV0LmdldEJ5dGVzKFN0YW5kYXJkQ2hhcnNldHMu
echo VVRGXzgpKSk7CiAgICAgICAgfSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsKICAgICAgICAgICAgdGhy
echo b3cgbmV3IElsbGVnYWxTdGF0ZUV4Y2VwdGlvbigiVW5hYmxlIHRvIHNpZ24gdG9rZW4iLCBlKTsK
echo ICAgICAgICB9CiAgICB9CgogICAgcHJpdmF0ZSBTdHJpbmcgYmFzZTY0VXJsKFN0cmluZyB2YWx1
echo ZSkgewogICAgICAgIHJldHVybiBCYXNlNjQuZ2V0VXJsRW5jb2RlcigpLndpdGhvdXRQYWRkaW5n
echo KCkuZW5jb2RlVG9TdHJpbmcodmFsdWUuZ2V0Qnl0ZXMoU3RhbmRhcmRDaGFyc2V0cy5VVEZfOCkp
echo OwogICAgfQoKICAgIHByaXZhdGUgU3RyaW5nIGVzY2FwZShTdHJpbmcgdmFsdWUpIHsKICAgICAg
echo ICByZXR1cm4gdmFsdWUucmVwbGFjZSgiXCIsICJcXCIpLnJlcGxhY2UoIiIiLCAiXCIiKTsKICAg
echo IH0KfQo=
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_service_AuthServiceImpl_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\service\AuthServiceImpl.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_service_AuthServiceImpl_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\controller" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\controller"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\controller\AuthController.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_controller_AuthController_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5jb250cm9sbGVyOwppbXBvcnQgY29t
echo LmJhbmtkZW1vLmJyYW5jaHNlcnZpY2UuZHRvLio7CmltcG9ydCBjb20uYmFua2RlbW8uYnJhbmNo
echo c2VydmljZS5zZXJ2aWNlLkF1dGhTZXJ2aWNlOwppbXBvcnQgb3JnLnNwcmluZ2ZyYW1ld29yay53
echo ZWIuYmluZC5hbm5vdGF0aW9uLio7CkBSZXN0Q29udHJvbGxlciBAUmVxdWVzdE1hcHBpbmcoIi9h
echo cGkvYXV0aCIpIHB1YmxpYyBjbGFzcyBBdXRoQ29udHJvbGxlciB7CiBwcml2YXRlIGZpbmFsIEF1
echo dGhTZXJ2aWNlIHNlcnZpY2U7IHB1YmxpYyBBdXRoQ29udHJvbGxlcihBdXRoU2VydmljZSBzZXJ2
echo aWNlKXt0aGlzLnNlcnZpY2U9c2VydmljZTt9CiBAUG9zdE1hcHBpbmcoIi9sb2dpbiIpIHB1Ymxp
echo YyBMb2dpblJlc3BvbnNlIGxvZ2luKEBSZXF1ZXN0Qm9keSBMb2dpblJlcXVlc3QgcmVxdWVzdCl7
echo cmV0dXJuIHNlcnZpY2UubG9naW4ocmVxdWVzdC5nZXRVc2VybmFtZSgpLHJlcXVlc3QuZ2V0UGFz
echo c3dvcmQoKSk7fQp9Cg==
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_controller_AuthController_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\controller\AuthController.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_controller_AuthController_java.b64" >nul 2>&1

if not exist "branch-service\src\main\java\com\bankdemo\branchservice\config" mkdir "branch-service\src\main\java\com\bankdemo\branchservice\config"
echo Writing branch-service\src\main\java\com\bankdemo\branchservice\config\SecurityConfig.java
> "%TEMP%\src_main_java_com_bankdemo_branchservice_config_SecurityConfig_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZS5jb25maWc7CmltcG9ydCBvcmcuc3By
echo aW5nZnJhbWV3b3JrLmNvbnRleHQuYW5ub3RhdGlvbi4qOwppbXBvcnQgb3JnLnNwcmluZ2ZyYW1l
echo d29yay5zZWN1cml0eS5jb25maWcuYW5ub3RhdGlvbi53ZWIuYnVpbGRlcnMuSHR0cFNlY3VyaXR5
echo OwppbXBvcnQgb3JnLnNwcmluZ2ZyYW1ld29yay5zZWN1cml0eS5jb25maWcuaHR0cC5TZXNzaW9u
echo Q3JlYXRpb25Qb2xpY3k7CmltcG9ydCBvcmcuc3ByaW5nZnJhbWV3b3JrLnNlY3VyaXR5LmNyeXB0
echo by5iY3J5cHQuQkNyeXB0UGFzc3dvcmRFbmNvZGVyOwppbXBvcnQgb3JnLnNwcmluZ2ZyYW1ld29y
echo ay5zZWN1cml0eS5jcnlwdG8ucGFzc3dvcmQuUGFzc3dvcmRFbmNvZGVyOwppbXBvcnQgb3JnLnNw
echo cmluZ2ZyYW1ld29yay5zZWN1cml0eS53ZWIuU2VjdXJpdHlGaWx0ZXJDaGFpbjsKQENvbmZpZ3Vy
echo YXRpb24gcHVibGljIGNsYXNzIFNlY3VyaXR5Q29uZmlnIHsKIEBCZWFuIFBhc3N3b3JkRW5jb2Rl
echo ciBwYXNzd29yZEVuY29kZXIoKXtyZXR1cm4gbmV3IEJDcnlwdFBhc3N3b3JkRW5jb2RlcigpO30K
echo IEBCZWFuIFNlY3VyaXR5RmlsdGVyQ2hhaW4gc2VjdXJpdHlGaWx0ZXJDaGFpbihIdHRwU2VjdXJp
echo dHkgaHR0cCl0aHJvd3MgRXhjZXB0aW9ue2h0dHAuY3NyZihjc3JmLT5jc3JmLmRpc2FibGUoKSku
echo c2Vzc2lvbk1hbmFnZW1lbnQocy0+cy5zZXNzaW9uQ3JlYXRpb25Qb2xpY3koU2Vzc2lvbkNyZWF0
echo aW9uUG9saWN5LlNUQVRFTEVTUykpLmF1dGhvcml6ZUh0dHBSZXF1ZXN0cyhhLT5hLnJlcXVlc3RN
echo YXRjaGVycygiL2FwaS9hdXRoL2xvZ2luIiwiL2FjdHVhdG9yL2hlYWx0aCIsIi9hY3R1YXRvci9p
echo bmZvIikucGVybWl0QWxsKCkuYW55UmVxdWVzdCgpLnBlcm1pdEFsbCgpKTsgcmV0dXJuIGh0dHAu
echo YnVpbGQoKTt9Cn0K
)
certutil -f -decode "%TEMP%\src_main_java_com_bankdemo_branchservice_config_SecurityConfig_java.b64" "branch-service\src\main\java\com\bankdemo\branchservice\config\SecurityConfig.java" >nul
del /q "%TEMP%\src_main_java_com_bankdemo_branchservice_config_SecurityConfig_java.b64" >nul 2>&1

if not exist "branch-service\src\test\java\com\bankdemo\branchservice" mkdir "branch-service\src\test\java\com\bankdemo\branchservice"
echo Writing branch-service\src\test\java\com\bankdemo\branchservice\BranchServiceApplicationTests.java
> "%TEMP%\src_test_java_com_bankdemo_branchservice_BranchServiceApplicationTests_java.b64" (
echo cGFja2FnZSBjb20uYmFua2RlbW8uYnJhbmNoc2VydmljZTsKaW1wb3J0IG9yZy5qdW5pdC5qdXBp
echo dGVyLmFwaS5UZXN0OwppbXBvcnQgb3JnLnNwcmluZ2ZyYW1ld29yay5ib290LnRlc3QuY29udGV4
echo dC5TcHJpbmdCb290VGVzdDsKQFNwcmluZ0Jvb3RUZXN0IGNsYXNzIEJyYW5jaFNlcnZpY2VBcHBs
echo aWNhdGlvblRlc3RzIHsgQFRlc3Qgdm9pZCBjb250ZXh0TG9hZHMoKSB7fSB9Cg==
)
certutil -f -decode "%TEMP%\src_test_java_com_bankdemo_branchservice_BranchServiceApplicationTests_java.b64" "branch-service\src\test\java\com\bankdemo\branchservice\BranchServiceApplicationTests.java" >nul
del /q "%TEMP%\src_test_java_com_bankdemo_branchservice_BranchServiceApplicationTests_java.b64" >nul 2>&1

echo Branch Service source written.
echo POM and application.properties were not modified.
pause
endlocal